# .github/workflows/cron-django.yml

name: Run Django Cron Job Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  django-cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10  # Use a supported version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Cron Logic
        env:
          DJANGO_SETTINGS_MODULE: pracproj.settings
        run: |
          python manage.py runserver # Replace with your custom command
