name: Keep Render Service Alive

on:
  schedule:
    # Runs every hour (adjust as needed)
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping the server
      run: |
        curl -f https://django-deploy-proj.onrender.com/ || curl -f https://django-deploy-proj.onrender.com/